-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreatePostRequiredArguments =
    { title : String }


createPost :
    CreatePostRequiredArguments
    -> SelectionSet decodesTo Api.Object.Post
    -> SelectionSet decodesTo RootMutation
createPost requiredArgs object_ =
    Object.selectionForCompositeField "createPost" [ Argument.required "title" requiredArgs.title Encode.string ] object_ identity


type alias UpdatePostOptionalArguments =
    { title : OptionalArgument String }


type alias UpdatePostRequiredArguments =
    { id : Float }


updatePost :
    (UpdatePostOptionalArguments -> UpdatePostOptionalArguments)
    -> UpdatePostRequiredArguments
    -> SelectionSet decodesTo Api.Object.Post
    -> SelectionSet (Maybe decodesTo) RootMutation
updatePost fillInOptionals requiredArgs object_ =
    let
        filledInOptionals =
            fillInOptionals { title = Absent }

        optionalArgs =
            [ Argument.optional "title" filledInOptionals.title Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "updatePost" (optionalArgs ++ [ Argument.required "id" requiredArgs.id Encode.float ]) object_ (identity >> Decode.nullable)


type alias DeletePostRequiredArguments =
    { id : Float }


deletePost :
    DeletePostRequiredArguments
    -> SelectionSet Bool RootMutation
deletePost requiredArgs =
    Object.selectionForField "Bool" "deletePost" [ Argument.required "id" requiredArgs.id Encode.float ] Decode.bool


type alias ChangePasswordRequiredArguments =
    { newPassword : String
    , token : String
    }


changePassword :
    ChangePasswordRequiredArguments
    -> SelectionSet decodesTo Api.Object.UserResponse
    -> SelectionSet decodesTo RootMutation
changePassword requiredArgs object_ =
    Object.selectionForCompositeField "changePassword" [ Argument.required "newPassword" requiredArgs.newPassword Encode.string, Argument.required "token" requiredArgs.token Encode.string ] object_ identity


type alias ForgotPasswordRequiredArguments =
    { email : String }


forgotPassword :
    ForgotPasswordRequiredArguments
    -> SelectionSet Bool RootMutation
forgotPassword requiredArgs =
    Object.selectionForField "Bool" "forgotPassword" [ Argument.required "email" requiredArgs.email Encode.string ] Decode.bool


type alias RegisterRequiredArguments =
    { options : Api.InputObject.UsernamePasswordInput }


register :
    RegisterRequiredArguments
    -> SelectionSet decodesTo Api.Object.UserResponse
    -> SelectionSet decodesTo RootMutation
register requiredArgs object_ =
    Object.selectionForCompositeField "register" [ Argument.required "options" requiredArgs.options Api.InputObject.encodeUsernamePasswordInput ] object_ identity


type alias LoginRequiredArguments =
    { password : String
    , usernameOrEmail : String
    }


login :
    LoginRequiredArguments
    -> SelectionSet decodesTo Api.Object.UserResponse
    -> SelectionSet decodesTo RootMutation
login requiredArgs object_ =
    Object.selectionForCompositeField "login" [ Argument.required "password" requiredArgs.password Encode.string, Argument.required "usernameOrEmail" requiredArgs.usernameOrEmail Encode.string ] object_ identity


logout : SelectionSet Bool RootMutation
logout =
    Object.selectionForField "Bool" "logout" [] Decode.bool
