-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type FieldError
    = FieldError


type PaginatedPosts
    = PaginatedPosts


type Post
    = Post


type User
    = User


type UserResponse
    = UserResponse
